[project]
name = "yiddish-grammar"
version = "0.1.0"
description = "א האנטבוך פאר אידישע שרייבער און מגיהים"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["mkdocs-material>=9.5.42"]
